// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tafhttyrrxmizdcffywx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZmh0dHlycnhtaXpkY2ZmeXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNTYwNTgsImV4cCI6MjA4MzYzMjA1OH0.g5p9I9ztmH_kuCU3FwXJL-SNqkm95wjeV5Y7BpehRsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});